using System.Diagnostics;
using OpenTelemetry;
using VirtoCommerce.Platform.Core.Common;


namespace VirtoCommerce.ApplicationInsights.Data.Telemetry;

/// <summary>
/// OpenTelemetry processor that suppresses activities whose urls match GraphQL related path but
/// <c>graphql.type</c> tag is empty meaning this activity was not generated by GraphQLHttpMiddlewareWithLogs.
/// Clearing the <see cref="ActivityTraceFlags.Recorded"/> flag prevents the activity
/// from being exported to Application Insights.
/// </summary>
public class IgnorePlainCoreXapiGraphQLTelemetryProcessor : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        var urlPath = activity?.GetTagItem("url.path")?.ToString();
        var graphQlTag = activity?.GetTagItem("graphql.type");
        if (urlPath != null && urlPath.ContainsIgnoreCase("/graphql") && graphQlTag == null)
        {
            activity.ActivityTraceFlags &= ~ActivityTraceFlags.Recorded;
        }
    }
}
