using System.Diagnostics;
using OpenTelemetry;
using VirtoCommerce.Platform.Core.Common;

namespace VirtoCommerce.Xapi.Core.Infrastructure;

/// <summary>
/// OpenTelemetry processor that suppresses activities that were not generated by GraphQLHttpMiddlewareWithLogs (graphql.type tag)
/// Clearing the 'ActivityTraceFlags.Recorded' flag prevents the activity from being exported to Application Insights.
/// </summary>
public class IgnorePlainCoreXapiGraphQLTelemetryProcessor : BaseProcessor<Activity>
{
    public override void OnEnd(Activity activity)
    {
        var urlPath = activity?.GetTagItem("url.path")?.ToString();
        var graphQlTag = activity?.GetTagItem("graphql.type");
        if (urlPath != null && urlPath.ContainsIgnoreCase("/graphql") && graphQlTag == null)
        {
            activity.ActivityTraceFlags &= ~ActivityTraceFlags.Recorded;
        }
    }
}
